In [26]:
import pandas as pd

#Consider the below code to answer further questions:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [27]:
list_

['1', '2', '3', '4', '5']

In [28]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [29]:
type(list_)

list

In [30]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [33]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [34]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [35]:
array_list = np.array(object = list_, dtype = int)

In [36]:
array_list

array([1, 2, 3, 4, 5])

In [37]:
# yes there is diffrece btween the data the type of list_ and array_list

for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [38]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [1]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [2]:
num_list

[[1, 2, 3], [4, 5, 6]]

num_array

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [3]:
print(num_array.size)
print(num_array.shape)

6
(2, 3)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [50]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
arr.size

9

In [49]:
arr.shape

(3, 3)

In [55]:
iarr = np.identity(5)
iarr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])